{% set version = "1.0.1" %}

package:
  name: sys-info-app
  version: {{ version }}

source:
  url: https://github.com/ablazhko/CondaCppApp/archive/4421c7bf047b54f084395dc9a58f7bf2704c05c4.zip
  sha256: 50acbe84c433b7fab31172f1e1540eee9e19af65a2e0c71ac74025b8b444d1e7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libzip
  run:
    - libzip

test:
  commands:
    - SystemInfoApp.exe

about:
  summary: "Simple C++ sys info app packaged with conda"